# Snake Animation Workflow
name: Generate Snake Animation

# Controls when the workflow will run
on:
  # Run automatically every day
  schedule:
    - cron: "0 0 * * *"
    
  # Allow manual trigger using the Actions tab
  workflow_dispatch:
  
  # Run on push to main branch
  push:
    branches:
    - main

# A workflow run is made up of one or more jobs
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Check out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      
      # Generate the snake animation
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # Output both SVG and GIF formats
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake-dark.gif?palette=github-dark
          
          # Snake animation settings
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Push to the "output" branch
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
